### ISSUE TITLE
Including this repository in other programs

### ISSUE THREAD

**Issue by jaredallard** [alekso56/ComputercraftLua#2]
Greetings, yes, I know this is not your code. However, I am writing a https://docker.io like application for computercraft and wanted to know how you feel about people including this code in other applications (from this repository), and if you know of any license bottlenecks that may occur.

**Comment by alekso56** [comment]
I have talked with dan about the lua code and others using it, and it's 100% a okay with him.
There is no license bottlenecks so far. 

Regards

**Comment by jaredallard** [comment]
Awesome, thanks for the quick response :)

Also, quick suggestion, on each version update I recommend you make a branch for it.

Thanks!

**Comment by alekso56** [comment]
Im not sure why you would need a branch for every commit / mc version.

**Comment by jaredallard** [comment]
i.e

```
git pull <repo>
git checkout <version>
```

Easier for tracking versions.

**Comment by alekso56** [comment]
You mean tagging?

```
checkout tags/<tag_name>
```

**Comment by jaredallard** [comment]
@alekso56 Ay, yes, sorry.

**Comment by alekso56** [comment]
Finally got around to tagging all the releases, here you go!  (lightweight tags)

**Comment by jaredallard** [comment]
Thanks very much mate!
