### ISSUE TITLE
Pastebin Program Broken

### ISSUE THREAD

**Issue by GoobyCorp** [alekso56/ComputercraftLua#3]
Pastebin swapped from the regular get args raw.php?i=(id) to a virtual directory /raw/(id) and it needs to be fixed in /rom/programs/http/pastebin on line 24.

**Comment by GoobyCorp** [comment]
IDK why I put this in here, this isn't an official git repo for the CC source.

**Comment by alekso56** [comment]
All issues you might have, should be directed at https://github.com/dan200/ComputerCraft/issues

**Comment by Wojbie** [comment]
You should post that here: https://github.com/dan200/ComputerCraft/issues
