### ISSUE TITLE
CTIF Image Converter Website AKA Contacting You is Hard

### ISSUE THREAD

**Issue by KeystrokeCascade** [alekso56/ComputercraftLua#5]
This was the only way I could find to possibly contact you and the most appropriate I could find.  Could you provide an offline version of your [ChenThread Image Converter](https://cax.no/conv/), as I know it's been up for 5 or so years, the original CTIF source is old, unmaintained and hard to get working, so I would like to have my own backup for it.

Hope this works and that I'm not bothering you.

**Comment by alekso56** [comment]
It's just a wrapper for the jar releases found here https://github.com/ChenThread/ctif/releases

**Comment by KeystrokeCascade** [comment]
Thanks! I'm not very good at this \:P
